### ISSUE TITLE
dynamic stance discovery

### ISSUE THREAD

**Issue by intrand** [reonZ/pf2e-stances#3]
Would you be willing to make this module search through all compendium packs for items with the `stance` trait instead of hard-coding a list? Such a change would allow this to work with custom content.

**Comment by reonZ** [comment]
you can add custom stances with the module.
also, not to mention the exceptions i do here and there, i dunno how taxing it would be to look through all the compendiums packs and world items on every load, some worlds can end up with loads of compendiums.

**Comment by reonZ** [comment]
hey, i took your idea and made it a reality, though because i am now merging most of my small modules into one, i have not done it in this module but directly made it a feature for the other one.

If you are interested, the module is called `PF2e ToolBelt` and the `Stances` features is dynamic

**Comment by intrand** [comment]
Thank you very much for looking into this! I'm glad you decided to implement it. Awesome!
